name = "Anneal"
uuid = "e4d9eb7f-b088-426e-aeb5-1c0dae3d8abb"
version = "0.5.2"
authors = [
    "pedromxavier <pedroxavier@psr-inc.com>",
    "AndradeTiago <tiago.andrade@psr-inc.com>",
    "joaquimg <joaquim@psr-inc.com>",
    "bernalde <dbernalneira@usra.edu>",
]

[deps]
BenchmarkTools = "6e4b80f9-dd63-53aa-95a3-0cdb28fa8baf"
JuMP = "4076af6c-e467-56ae-b986-b466b2749572"
MathOptInterface = "b8f27783-ece8-5eb3-8dc8-9495eed66fee"
QUBOTools = "60eb5b62-0a39-4ddc-84c5-97d2adff9319"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[compat]
BenchmarkTools = "1.3"
JuMP = "1"
MathOptInterface = "1"
QUBOTools = "0.4.2"
julia = "1.6"
